[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
  map <C-n> <plug>NERDTreeTabsToggle<CR>
'''
depends = ['nerttree']

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#show_buffers = 0
  let g:airline#extensions#tabline#tab_nr_type = 1
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#ale#enabled = 1
  let g:airline#extensions#tagbar#enabled = 1
'''

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo =  'scrooloose/syntastic'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = '42Paris/42header'
hook_add = '''
  let g:user42 = "rkurimot"
  let g:mail42 = "rkurimot@student.42tokyo.jp"
  nnoremap <silent> <C-A-h> :Stdheader<CR>
'''
