[tools]
# Development tools
codex = "latest"

# Runtimes and toolchains
ghcup = "latest"
node = "lts"
rust = "latest"
uv = "latest"

# CLI tools
bat = "latest"
eza = "0.23.4"     # latest not found
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
hexyl = "latest"
jq = "latest"
procs = "latest"
ripgrep = "latest"
tokei = "latest"
usage = "latest"
yq = "latest"
zoxide = "latest"

[tool_alias]
procs = "github:dalance/procs"
