[tools]
"usage" = "latest"

# Runtimes and toolchains
"ghcup" = "latest"
"node" = "lts"
"rust" = "latest"
"uv" = "latest"

# CLI tools
"aqua:sharkdp/bat" = "latest"
"aqua:Wilfred/difftastic" = "latest"
"github:eza-community/eza" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:cli/cli" = "latest"
"aqua:sharkdp/hexyl" = "latest"
"aqua:jqlang/jq" = "latest"
"github:dalance/procs" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:XAMPPRocky/tokei" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
